import Head from "next/head";
import Script from "next/script";
import { Canvas, useFrame, extend } from "@react-three/fiber";
import { Suspense, useMemo, useRef, useState } from "react";
import Mesh from "../components/Mesh/Mesh";
import { PerformanceMonitor } from "@react-three/drei";
import {Loader} from '../components/Loader/Loader'
import Spinner from "../components/Spinner/Spinner";


export default function Home() {
  const [dpr, setDpr] = useState(1.5);
  return (
    <div>
      <Head>
        <title>React Three Fiber Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="bg-[#f1f1f1] h-[100vh] w-[100vw]">
    
      <Suspense fallback={<Spinner />}>
        <Canvas shadows dpr={dpr}>
            <Mesh/>
          <PerformanceMonitor onIncline={() => setDpr(2)} onDecline={() => setDpr(1)} ></PerformanceMonitor>
        </Canvas>
        </Suspense>
      
        <Loader/>

      </div>

    </div>
  );
}
